# Generated by Django 6.0.2 on 2026-08-06 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='household',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Mahayahay', 'Mahayahay'), ('Tambacan', 'Tambacan'), ('Abuno', 'Abuno'), ('Hinaplanon', 'Hinaplanon'), ('Pala-o Riverside', 'Pala-o Riverside'), ('Tubod', 'Tubod'), ('Tipanoy', 'Tipanoy'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='household',
            name='dwelling_type',
            field=models.CharField(blank=True, choices=[('concrete', 'Concrete'), ('semi_concrete', 'Semi-concrete'), ('wood', 'Wood / Light materials'), ('makeshift', 'Makeshift / Informal settler structure')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='is_four_ps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='household',
            name='purok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='household',
            name='registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('relation', models.CharField(choices=[('Head', 'Head of Household'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Grandchild', 'Grandchild'), ('Other', 'Other')], default='Other', max_length=20)),
                ('is_pwd', models.BooleanField(default=False)),
                ('pwd_detail', models.CharField(blank=True, max_length=255)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('pregnant_detail', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='accounts.household')),
            ],
        ),
    ]
