# Generated by Django 6.0.2 on 2026-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_household_address_line_household_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
