# Generated by Django 6.0.2 on 2026-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_household_status_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='barangay',
            field=models.CharField(blank=True, choices=[('Mahayahay', 'Mahayahay'), ('Tambacan', 'Tambacan'), ('Abuno', 'Abuno'), ('Hinaplanon', 'Hinaplanon'), ('Pala-o Riverside', 'Pala-o Riverside'), ('Tubod', 'Tubod'), ('Tipanoy', 'Tipanoy')], max_length=50),
        ),
    ]
