# Generated by Django 6.0.2 on 2026-09-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_household_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
            },
        ),
        migrations.CreateModel(
            name='DisasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='household',
            name='barangay_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='accounts.barangay'),
        ),
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('barangay', models.CharField(choices=[('Mahayahay', 'Mahayahay'), ('Tambacan', 'Tambacan'), ('Abuno', 'Abuno'), ('Hinaplanon', 'Hinaplanon'), ('Pala-o Riverside', 'Pala-o Riverside'), ('Tubod', 'Tubod'), ('Tipanoy', 'Tipanoy')], max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('barangay_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evacuation_centers', to='accounts.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Checked Out', 'Checked Out')], default='Present', max_length=15)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.familymember')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.household')),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='accounts.disastertype')),
                ('evacuation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.evacuationcenter')),
            ],
        ),
    ]
