# Generated by Django 6.0.2 on 2026-09-10 06:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_barangay_disastertype_household_barangay_fk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=150)),
                ('contact_num', models.CharField(blank=True, max_length=20)),
                ('goods_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('distributed', 'Distributed')], default='pending', max_length=15)),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='accounts.disastertype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
