# Generated by Django 6.0.7 on 2026-09-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_relief_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='gps_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='gps_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
