# Generated by Django 6.0.2 on 2026-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AlterField(
            model_name='evacuationcenter',
            name='barangay',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='household',
            name='barangay',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
