# Generated by Django 6.0.7 on 2026-09-08 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_evacuationcenter_gps_lat_evacuationcenter_gps_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(blank=True, choices=[('Mahayahay', 'Mahayahay'), ('Tambacan', 'Tambacan'), ('Abuno', 'Abuno'), ('Hinaplanon', 'Hinaplanon'), ('Pala-o Riverside', 'Pala-o Riverside'), ('Tubod', 'Tubod'), ('Tipanoy', 'Tipanoy')], help_text='Leave blank for a city-wide advisory.', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='accounts.disastertype')),
            ],
            options={
                'verbose_name_plural': 'Advisories',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.advisory')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.household')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
