# Generated by Django 6.1.1 on 2026-09-10 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_donation_user_alter_evacuationcenter_barangay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('distributed_by', models.CharField(blank=True, max_length=150)),
                ('distributed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_distributions', to='accounts.disastertype')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_records', to='accounts.household')),
            ],
            options={
                'ordering': ['-distributed_at'],
            },
        ),
    ]