# Generated by Django 6.0.2 on 2026-09-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='disaster_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_by',
        ),
        migrations.AddField(
            model_name='barangay',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evacuationcenter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DisasterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='accounts.disastertype')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='EvacuationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('route_distance', models.CharField(blank=True, max_length=50)),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('road_condition', models.CharField(choices=[('clear', 'Clear'), ('passable', 'Passable'), ('flooded', 'Flooded'), ('landslide_risk', 'Landslide Risk'), ('impassable', 'Impassable')], default='clear', max_length=20)),
                ('route_status', models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('blocked', 'Blocked')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evacuation_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuation_routes', to='accounts.evacuationcenter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_areas', to='accounts.disastertype')),
            ],
            options={
                'ordering': ['-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(blank=True, help_text='Leave blank to estimate from the barangay coordinates.', null=True)),
                ('road_condition', models.CharField(choices=[('clear', 'Clear'), ('passable', 'Passable'), ('flooded', 'Flooded'), ('landslide_risk', 'Landslide Risk'), ('impassable', 'Impassable')], default='clear', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_segments_out', to='accounts.barangay')),
                ('to_barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_segments_in', to='accounts.barangay')),
            ],
            options={
                'ordering': ['from_barangay__barangay_name', 'to_barangay__barangay_name'],
                'unique_together': {('from_barangay', 'to_barangay')},
            },
        ),
        migrations.DeleteModel(
            name='ReliefDistribution',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
