# Generated by Django 6.0.2 on 2026-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_report_disaster_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskarea',
            name='disaster_type',
        ),
        migrations.AlterUniqueTogether(
            name='roadsegment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='from_barangay',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='to_barangay',
        ),
        migrations.AlterField(
            model_name='evacuationroute',
            name='route_status',
            field=models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('blocked', 'Blocked'), ('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='active', max_length=15),
        ),
        migrations.DeleteModel(
            name='DisasterLocation',
        ),
        migrations.DeleteModel(
            name='RiskArea',
        ),
        migrations.DeleteModel(
            name='RoadSegment',
        ),
    ]
