# Generated by Django 6.1.1 on 2026-09-27 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_relief_stock(apps, schema_editor):
    """Creates the two stock rows (rice, pack) at zero so the dashboard
    always has something to read/update instead of a missing row."""
    ReliefStock = apps.get_model('accounts', 'ReliefStock')
    for goods_type in ('rice', 'pack'):
        ReliefStock.objects.get_or_create(goods_type=goods_type, defaults={'quantity': 0})


def unseed_relief_stock(apps, schema_editor):
    ReliefStock = apps.get_model('accounts', 'ReliefStock')
    ReliefStock.objects.filter(goods_type__in=('rice', 'pack')).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_riskarea_disaster_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(choices=[('rice', 'Rice'), ('pack', 'Pack')], max_length=10, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['goods_type'],
            },
        ),
        migrations.CreateModel(
            name='ReliefDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(choices=[('rice', 'Rice'), ('pack', 'Pack')], max_length=10)),
                ('quantity_given', models.PositiveIntegerField(default=0)),
                ('distribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tracking_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('claim_status', models.CharField(choices=[('claimed', 'Claimed'), ('pending', 'Pending')], default='claimed', max_length=10)),
                ('distributed_by', models.CharField(blank=True, max_length=150)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('disaster_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_distributions', to='accounts.disastertype')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_records', to='accounts.household')),
            ],
            options={
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.RunPython(seed_relief_stock, unseed_relief_stock),
    ]
