# Generated by Django 6.0.7 on 2026-09-27 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_reliefstock_reliefdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purok_name', models.CharField(max_length=100)),
                ('route_description', models.TextField(blank=True)),
                ('route_distance', models.CharField(blank=True, max_length=50)),
                ('estimated_time', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puroks', to='accounts.barangay')),
            ],
            options={
                'verbose_name_plural': 'Puroks',
                'unique_together': {('barangay', 'purok_name')},
            },
        ),
        migrations.AddField(
            model_name='household',
            name='purok_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='accounts.purok'),
        ),
    ]
