# Generated by Django 6.0.2 on 2026-10-03 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_purok_household_purok_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(choices=[('rice', 'Rice'), ('pack', 'Pack')], max_length=10)),
                ('movement', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('quantity', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('distribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='accounts.reliefdistribution')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='accounts.donation')),
            ],
            options={
                'verbose_name': 'Relief inventory entry',
                'verbose_name_plural': 'Relief inventory',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
