# Generated by Django 6.0.2 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_reliefinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefdistribution',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reliefdistribution',
            name='status_updated_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='reliefdistribution',
            name='claim_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready for Pickup'), ('claimed', 'Claimed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='processing', max_length=10),
        ),
    ]
