# Generated by Django 6.0.2 on 2026-10-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_reliefdistribution_claimed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefdistribution',
            name='goods_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reliefstock',
            name='goods_type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ReliefInventory',
        ),
    ]
