# Generated by Django 6.0.2 on 2026-10-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
