# Generated by Django 6.0.2 on 2026-10-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefdistribution',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_distributions', to='accounts.barangay'),
        ),
        migrations.AddField(
            model_name='reliefdistribution',
            name='evacuation_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_distributions', to='accounts.evacuationcenter'),
        ),
        migrations.AddField(
            model_name='reliefdistribution',
            name='households_served',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reliefdistribution',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relief_records', to='accounts.household'),
        ),
    ]
