# Generated by Django 6.0.2 on 2026-10-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vulnerabilityprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='is_four_ps',
        ),
    ]
