# Generated by Django 6.0.2 on 2026-10-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_household_is_four_ps'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='family_members/'),
        ),
    ]
