from django.urls import path
from .views import (
    login_user,
    cswd_dashboard,
    cswd_add_donation,
    drrm_dashboard,
    drrm_routes,
    drrm_disaster_types,
    drrm_add_disaster_type,
    drrm_update_disaster_type,
    drrm_delete_disaster_type,
    drrm_update_route,
    drrm_map,
    drrm_fastest_route,
    drrm_set_risk_area,
    drrm_add_evacuation_center,
    drrm_delete_evacuation_center,
    barangay_dashboard,
    barangay_confirm_household,
    barangay_evacuation_dashboard,
    attendance_scan,
    purok_dashboard,
    purok_review_household,
    register_resident,
    register_complete,
    register_lookups,
    login_resident,
    resident_dashboard,
    resident_nearest_route,
)

urlpatterns = [
    path('login/', login_user, name='login'),
    path("cswd/dashboard/", cswd_dashboard),
    path("cswd/donations/add/", cswd_add_donation),
    path("drrm/dashboard/", drrm_dashboard),
    path("drrm/routes/", drrm_routes),
    path("drrm/disaster-types/", drrm_disaster_types),
    path("drrm/disaster-types/add/", drrm_add_disaster_type),
    path("drrm/disaster-types/update/", drrm_update_disaster_type),
    path("drrm/disaster-types/delete/", drrm_delete_disaster_type),
    path("drrm/routes/update/", drrm_update_route),
    path("drrm/map/", drrm_map),
    path("drrm/fastest-route/", drrm_fastest_route),
    path("drrm/risk-areas/set/", drrm_set_risk_area),
    path("drrm/evacuation-centers/create/", drrm_add_evacuation_center),
    path("drrm/evacuation-centers/delete/", drrm_delete_evacuation_center),
    path("barangay/dashboard/", barangay_dashboard),
    path("barangay/households/<str:household_code>/confirm/", barangay_confirm_household),
    path("barangay/evacuation/dashboard/", barangay_evacuation_dashboard),
    path("barangay/attendance/scan/", attendance_scan),
    path("purok/dashboard/", purok_dashboard),
    path("purok/households/<str:household_code>/review/", purok_review_household),

    # Resident app (GEOAID_resident)
    path("resident/register/", register_resident),
    path("resident/register/lookups/", register_lookups),
    path("resident/register/complete/", register_complete),
    path("resident/login/", login_resident),
    path("resident/dashboard/", resident_dashboard),
    path("resident/evacuation/nearest-route/", resident_nearest_route),
]